[package]
name = "mdvault"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "0.4.18"
thiserror = "1.0.29"

[dev-dependencies]
assert_fs = "1.0.5"
